import { defineConfig } from 'tsup'

/**
 * Build every entry bundle in one pass. Each bundle is self-contained:
 * an entry only references its own provider, so the other providers'
 * signing code is never reached — the shared op/protocol layer imports
 * no signer — and bundling drops it. Consumers get a single standalone
 * file per entry (see `exports` in package.json).
 *
 * Entry keys carry the full `.es` stem so each key maps to
 * `tiny-oss<.suffix>.es.js`. The matching `tiny-oss<.suffix>.es.d.ts`
 * is generated by dts-bundle-generator (the `build:types:*` scripts),
 * not by tsup: tsup's multi-entry dts worker splits shared modules
 * into hashed chunks that its entry files import as `.js` paths, while
 * this build emits no JS chunks — the references would dangle.
 */
export default defineConfig({
  entry: {
    'tiny-oss.es': 'src/index.ts',
    'tiny-oss.cos.es': 'src/cos/index.ts',
    'tiny-oss.obs.es': 'src/obs/index.ts',
    'tiny-oss.aws.es': 'src/aws/index.ts',
    'tiny-oss.azure.es': 'src/azure/index.ts',
    'tiny-oss.protocol.es': 'src/provider.ts',
  },
  format: ['esm'],
  target: 'es2020',
  outDir: 'dist',
  clean: true,
  splitting: false,
  sourcemap: true,
  minify: true,
  // js-base64 must stay inlined: the bundles are consumed directly by
  // browsers (see example/) as standalone files, not through a bundler
  // that would resolve the import.
  noExternal: ['js-base64'],
})
